[logging]
checker = "debug"
default = "info"

[docker]
connect_uri = "unix:///var/run/docker.sock"
# currently tls isn't a priority, but adding it should be simple
tls = true
# purge containers from stats map if they aren't seen for purge_unseen seconds
purge_unseen = 100

[containers]
# if you will use default catch-all patter and you'll run docker-check in container you should filter it by label or adjust the filter regex
filter_by = ".*"
# Allows to filter container with docker-check based on that regex. 
filter_self = "skipme"
# Regulates which fields from docker api are used in filtering containers
# Valid values are: 
#  - name
#  - image
#  - label
apply_filter_to = ['name', 'image', 'label']
consecutive_failures = 5
hard_failures = 3
# can be absolute or relative path
# currently run with "$run_on_failure %c" 
# where %c is container-id
run_on_failure = "example/notify-slack.sh"

# Note: label filters are filled separately from rest of containers config. 
# Thats because it's a map and the parser will parse everything as map key=value until it encounters another table(section)
[containers.label_filters]
 "im.lain.docker-check" = "skipme"

[aws]
enabled = true
  [aws.asg]
  healthcheck = true
