[logging]
checker = "debug"
default = "warn"

[docker]
connect_uri = "unix:///var/run/docker.sock"
tls = true

[containers]
filter_by = ".*"
consecutive_failures = 5
hard_failures = 3

[aws]
enabled = true
[aws.asg]
healthcheck = true
